<?php
$purchase = $this->getCurrent();
$isEditing = $purchase->status == 'EDITTNG';
?>

<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>
                <?php echo $isEditing ? 'Nueva' : ''; ?> Compra
            </h4>
        </div>
        <div class="flex-fill text-end pt-2 pe-2">
            <a class="btn btn-sm btn-outline-<?php echo $isEditing ? 'success' : 'primary'; ?>" href="#"
                id="<?php echo $isEditing ? 'finish' : 'edit'; ?>">
                <i class="bi bi-<?php echo $isEditing ? 'check-circle' : 'pencil-square'; ?>"></i>
                <?php echo $isEditing ? 'Finalizar' : 'Editar'; ?>
            </a>
        </div>
    </div>
</div>

<div class="d-flex my-2 mx-2">
    <div class="p-1 flex-grow-1">
        <div style="font-size:10px;">Proveedor</div>
        <?php echo $purchase->supplier; ?>
    </div>
    <div class="p-1">
        <div style="font-size:10px;">Fecha</div>
        <?php echo date('d M Y', strtotime($purchase->date)); ?>
    </div>
</div>

<?php
if ($isEditing) {
    $tab = $this->getTab();
    $products = $tab == '1' ? $this->getProductsToAdd($purchase->id) : $this->getProducts($purchase->id);
    $params = "preAction=editPurchase&purchaseId=$purchase->id&tab=$tab";
    ?>

    <ul class="nav nav-tabs mx-1" style="font-size: 14px;">
        <li class="nav-item">
            <a class="nav-link <?php echo $tab == '1' ? 'active' : ''; ?>" ref="#" id="tabAdd">
                <i class="bi bi-plus"></i> Agregar
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php echo $tab == '2' ? 'active' : ''; ?>" href="#" id="tabList">
                <i class="bi bi-list-check"></i> Listado
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="#" id="search">
                <i class="bi bi-search"></i> Buscar
            </a>
        </li>
    </ul>

    <?php $this->search($params); ?>

    <div class="<?php echo $tab == '1' ? '' : 'accordion'; ?> mt-2 mb-3" id="accordionExample">
        <div class="d-flex mb-1 border-bottom">
            <div class="flex-grow-1 ms-2">
                Producto
            </div>
            <div class="me-5">
                Cantidad
            </div>
        </div>
        <?php
        foreach ($products as $product) {
            if ($tab == '1') { ?>
                <div class="d-flex">
                    <div class="flex-grow-1 p-1" style="font-size: 13px;">
                        <?php echo $product->name; ?>
                        <div style="font-size: 8px;">
                            <?php echo $product->description; ?>
                        </div>
                    </div>
                    <div class="p-1">
                        <input type="number" class="form-control" id="quantity<?php echo $product->id; ?>" placeholder="0"
                            style="width: 75px;">
                    </div>
                    <div class="p-1">
                        <button type="button" class="btn btn-primary" id="prod<?php echo $product->id; ?>">
                            <i class="bi bi-plus-lg"></i>
                        </button>
                    </div>
                </div>
                <hr class="my-0">
            <?php
            } else {
                ?>
                <div class="accordion-item px-0">
                    <h2 class="accordion-header" id="head<?php echo $product->id; ?>">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapse<?php echo $product->id; ?>" aria-expanded="false"
                            aria-controls="collapse<?php echo $product->id; ?>">
                            <div class="d-flex me-1" style="width: 100%;">
                                <div class="flex-grow-1">
                                    <?php echo $product->name; ?>
                                </div>
                                <div class="ps-1 text-end">
                                    <?php echo $product->quantity; ?>
                                </div>
                            </div>
                        </button>
                    </h2>
                    <div id="collapse<?php echo $product->id; ?>" class="accordion-collapse collapse"
                        aria-labelledby="head<?php echo $product->id; ?>" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div class="input-group">
                                <input type="number" class="form-control" placeholder="0" value="<?php echo $product->quantity; ?>"
                                    aria-label="Cantidad de producto" id="quantity<?php echo $product->movId; ?>">
                                <button class="btn btn-outline-success" type="button" id="save<?php echo $product->movId; ?>">
                                    <i class="bi bi-save"></i>
                                    Guardar
                                </button>
                                <button class="btn btn-outline-danger" type="button" id="del<?php echo $product->movId; ?>">
                                    <i class="bi bi-trash"></i>
                                    Eliminar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php
            }
        } ?>
    </div>

    <?php $this->pagination($params); ?>

<?php
} else {
    $products = $this->getAllProducts($purchase->id);
    ?>
    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($products as $product) {
                ?>
                <tr>
                    <td>
                        <?php echo $product->name; ?>
                        <div style="font-size: 8px;">
                            <?php echo $product->description; ?>
                        </div>
                    </td>
                    <td class="text-end align-middle pe-3">
                        <?php echo $product->quantity; ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php
}
?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("purchase", "index", "#view", "");
            });
            $("#tabAdd").click(function () {
                show("purchase", "editPurchase", "#view", "purchaseId=<?php echo $purchase->id; ?>&tab=1");
            });
            $("#tabList").click(function () {
                show("purchase", "editPurchase", "#view", "purchaseId=<?php echo $purchase->id; ?>&tab=2");
            });
            $("#finish").click(function () {
                show("purchase", "finish", "#view", "purchaseId=<?php echo $purchase->id; ?>");
            });
            $("#edit").click(function () {
                show("purchase", "backToEdit", "#view", "purchaseId=<?php echo $purchase->id; ?>");
            });

            <?php
            if ($isEditing) {
                foreach ($products as $product) {
                    if ($tab == '1') { ?>
                        $("#prod<?php echo $product->id; ?>").click(function () {
                            show("purchase", "addProduct", "#view",
                                "<?php echo $params ?>&quantity=" + $("#quantity<?php echo $product->id; ?>").val()
                                + "&productId=<?php echo $product->id; ?>");
                        });
                    <?php
                    } else {
                        ?>
                        $("#save<?php echo $product->movId; ?>").click(function () {
                            show("purchase", "updateQuantity", "#view",
                                "<?php echo $params ?>&quantity=" + $("#quantity<?php echo $product->movId; ?>").val()
                                + "&movId=<?php echo $product->movId; ?>");
                        });

                        $("#del<?php echo $product->movId; ?>").click(function () {
                            show("purchase", "deleteMovement", "#view",
                                "<?php echo $params ?>&movId=<?php echo $product->movId; ?>");
                        });
                    <?php
                    }
                }
            }
            ?>
        });
    });
</script>