<?php $purchases = $this->getAllPurchases(); ?>

<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4><i class="bi bi-cart"></i> Compras</h4>
        </div>
        <button class="btn btn-link" id="search">
            <i class="bi bi-search" style='font-size:24px'></i>
        </button>
        <button class="btn btn-link" id="add">
            <i class="bi bi-plus-lg" style='font-size:27px'></i>
        </button>
    </div>
</div>

<?php $this->search(); ?>

<table class="table">
    <thead>
        <tr>
            <th colspan="2">Proveedor</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($purchases as $purchase) {
            $editing = $purchase->status == 'EDITTNG';
            $badge = $editing ? 'info' : 'success';
            $status = $editing ? 'Pendiente' : 'Aplicada';
            $icon = $editing ? 'pencil-square' : 'eye';
            ?>
            <tr>
                <td>
                    <?php echo $purchase->supplier; ?>
                    <div style="font-size:11px;">
                        <span class="badge text-bg-<?php echo $badge; ?>">
                            <?php echo $status; ?>
                        </span>
                        <?php echo date('d M Y', strtotime($purchase->date)); ?>
                    </div>
                </td>
                <td class="text-end align-middle">
                    <button class="btn btn-link m-0 p-0" id="purchase<?php echo $purchase->id; ?>">
                        <i class="bi bi-<?php echo $icon; ?>" style='font-size:23px'></i>
                    </button>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "admin", "#view", "");
            });
            $("#add").click(function () {
                show("purchase", "selectSupplier", "#view", "");
            });
            <?php foreach ($purchases as $purchase) { ?>
                $("#purchase<?php echo $purchase->id; ?>").click(function () {
                    show("purchase", "editPurchase", "#view", "purchaseId=<?php echo $purchase->id; ?>");
                });
            <?php } ?>
        });
    });
</script>