<?php
$suppliers = $this->getAllSuppliers();
?>
<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill pt-3">
            <h4><i class="bi bi-cart-plus"></i> Nueva Compra</h4>
        </div>
        <button class="btn btn-link" id="search">
            <i class="bi bi-search" style='font-size:24px'></i>
        </button>
    </div>
</div>

<?php $this->search(); ?>

<table class="table">
    <thead>
        <tr>
            <th>Selecciona Proveedor</th>
            <th class="text-end">
                <button class="btn btn-primary btn-sm" id="add-supplier">
                    <i class="bi bi-plus-lg"></i> Crear Proveedor
                </button>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($suppliers as $supplier) { ?>
            <tr>
                <td class="align-middle">
                    <?php echo $supplier->name; ?>
                </td>
                <td class="text-end">
                    <button class="btn btn-primary btn-sm" id="select<?php echo $supplier->id; ?>">
                        <i class="bi bi-plus-lg"></i>
                    </button>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("purchase", "index", "#view", "");
            });
            <?php foreach ($suppliers as $supplier) { ?>
                $("#select<?php echo $supplier->id; ?>").click(function () {
                    show("purchase", "edit", "#view", "supplierId=<?php echo $supplier->id; ?>");
                });
            <?php } ?>
        });
    });
</script>