<?php
$params = $this->getExtraParams();
?>

<form class="was-validated" id="form-filter" action="javascript:void(0);" enctype="multipart/form-data">
    <div class="input-group">
        <input type="text" name="datafilter" class="form-control" placeholder="Buscar..."
            value="<?php echo $this->getFilter(); ?>" required autofocus>
        <button class="btn btn-primary" type="submit">
            <i class="bi bi-search"></i>
        </button>
        <button class="btn btn-danger" id="clear">
            <i class="bi bi-x"></i>
        </button>
    </div>
</form>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#clear").click(function () {
                show("<?php echo $this->controller; ?>", "<?php echo $this->getPreAction(); ?>", "#view", "<?php echo $params; ?>");
            });
            $("#form-filter").submit(function (event) {
                show("<?php echo $this->controller; ?>",
                    "<?php echo $this->getPreAction(); ?>", "#view",
                    $(this).serialize() + "<?php echo $params = $params == '' ? '' : "&$params"; ?>");
            });
        });
    });
</script>