<?php
$page = $this->getPage();
$pages = $this->getPages();
$startPage = $this->getStartPage();
$pageList = $this->getPageList();
$filter = $this->getFilter();
?>

<?php if ($pages > 1) { ?>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php if ($pages > 5) { ?>
                <button class="page-link" id="prev" <?php echo $startPage == 1 ? 'disabled' : ''; ?>>
                    <i class="bi bi-chevron-compact-left"></i>
                </button>
            <?php } ?>
            <?php foreach ($pageList as $item) { ?>
                <li class="page-item <?php echo $item == $page ? 'active' : ''; ?>">
                    <button class="page-link" id="p<?php echo $item; ?>">
                        <?php echo $item; ?>
                    </button>
                </li>
            <?php } ?>
            <?php if ($pages > 5) { ?>
                <button class="page-link" id="next" <?php echo ($startPage + 4) == $pages ? 'disabled' : ''; ?>>
                    <i class="bi bi-chevron-compact-right"></i>
                </button>
            <?php } ?>
        </ul>
    </nav>
<?php } ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
<?php if ($pages > 5) { ?>

        <?php if ($startPage != 1) { ?>
                            $("#prev").click(function () {
                                show("<?php echo $this->controller; ?>", "<?php echo $this->action; ?>", "#view",
                                    "page=<?php echo $startPage - 1; ?>&startPage=<?php echo $startPage;
                                         echo $filter == '' ? '' : "&datafilter=$filter";?>");
                            });  
        <?php } ?>
    
        <?php if (($startPage + 4) != $pages) { ?>
                            $("#next").click(function () {
                                show("<?php echo $this->controller; ?>", "<?php echo $this->action; ?>", "#view",
                                    "page=<?php echo $startPage + 5; ?>&startPage=<?php echo $startPage; 
                                        echo $filter == '' ? '' : "&datafilter=$filter";?>");
                            }); 
        <?php } ?>

<?php } ?>

<?php foreach ($pageList as $item) { ?>
                    $("#p<?php echo $item; ?>").click(function () {
                        show("<?php echo $this->controller; ?>", "<?php echo $this->action; ?>", "#view",
                            "page=<?php echo $item; ?>&startPage=<?php echo $startPage; 
                                echo $filter == '' ? '' : "&datafilter=$filter";?>");
                    });  
<?php } ?>
        });
    });
</script>