<?php 
    $table = $this->table;
    $reg = $this->table->getById($_REQUEST['IdView']); 
?>
<div class="modal-body">
    <?php 
    foreach($reg as $key => $value)	{
        if (!$table->hideFieldView($key)) {
            if ($table->isImage($key)) {
    ?>
    <div class="row mb-1 ml-1 mr-1">
        <div class="col-sm-4 bg-secondary text-white"><?php echo strtr($key,"_"," ");?></div>
        <div class="col bg-light">
            <img src="<?php echo $value;?>" class="img-fluid" alt="Responsive image">
        </div>
    </div>
    <?php
            } else {
                $value = $this->table->hasCatalogo($key) ? $this->table->getValCatalogo($key, $value) : $value;
                $class = '';
                if ($this->is_Date($value)) {
                    $value = date('Y-m-d',strtotime($value));
                } else if ($this->table->isMoney($key)) {
                    $value = 'Q.'.number_format($value, 2, '.', '');
                    $class = 'text-right';
                }
    ?>
    <div class="row mb-1 ml-1 mr-1">
        <div class="col-sm-4 bg-secondary text-white"><?php echo strtr($key,"_"," ");?></div>
        <div class="col bg-light <?php echo $class;?> text-break"><?php echo $value;?></div>
    </div>
    <?php
            } // else isImage
        }  //hideFieldView
    } // foreach 
    ?>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-outline-primary" data-dismiss="modal" id="edit">
        <i class="bi bi-pencil-square" style='font-size:17px'></i>
        Editar
    </button>
    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
        <i class="bi bi-x-circle-fill" style='font-size:17px'></i>
        Close
    </button>
</div>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
		    $("#edit").click(function() {
                setTimeout(function() { 
        			show("<?php echo $this->controller; ?>", "edit", "#view", "IdEdit=<?php echo $reg->Id;?>");
                }, 500);
        	});
        });
	});
</script>