<?php
$supplier = $this->getSupplier();
$new = $supplier->id == '';
?>
<div class="fixed-top bg-light border-bottom sticky-top">
  <div class="d-flex bd-highlight">
    <div class="flex-fill text-left">
      <button class="btn btn-link" id="back">
        <i class="bi bi-chevron-left" style='font-size:27px'></i>
      </button>
    </div>
    <div class="flex-fill text-center pt-3">
      <h4>
        <?php echo $new ? 'Crear' : 'Editar'; ?> Proveedor
      </h4>
    </div>
    <div class="flex-fill text-end pt-1">
      <i class="bi bi-<?php echo $new ? 'plus' : 'pencil'; ?>-square me-3" style='font-size:30px'></i>
    </div>
  </div>
</div>

<div class="container">
  <form class="form-floating was-validated" id="form" action="javascript:void(0);" enctype="multipart/form-data">
    <input name="id" type="hidden" value="<?php echo $supplier->id; ?>" />

    <div class="form-floating my-2">
      <input type="text" class="form-control" name="name" placeholder="nombre" value="<?php echo $supplier->name; ?>"
        required autofocus>
      <label for="floatingInput">Nombre</label>
    </div>

    <div class="form-floating mb-2">
      <input type="text" class="form-control" name="description" placeholder="Descripcion"
        value="<?php echo $supplier->description; ?>">
      <label for="floatingInput">Descripción</label>
    </div>

    <div class="form-floating mb-2">
      <input type="number" name="phone" placeholder="Telefono" value="<?php echo $supplier->phone; ?>"
        class="form-control" step="1" placeholder='55555555' min="10000000" max="99999999" required>
      <label for="floatingInput">Teléfono</label>
    </div>

    <div class="text-end mt-3">
      <button class="btn btn-primary" type="submit">
        <i class="bi bi-save"></i>
        Guardar
      </button>
      <?php if (!$nuevo) { ?>
        <button class="btn btn-danger" id="delete">
          <i class="bi bi-trash"></i>
          Eliminar
        </button>
      <?php } ?>
    </div>
  </form>
</div>

<script>
  $(document).ready(function () {
    $.getScript("lib/vcl/nav.js", function () {
      $("#back").click(function () {
        show("supplier", "index", "#view", "<?php echo $this->getBackFiltered(); ?>");
      });
      $("#form").submit(function (event) {
        show("supplier", "save", "#view", $(this).serialize());
      });
      $("#delete").click(function () {
        show("supplier", "delete", "#view", "id=<?php echo $supplier->id; ?>");
      });
    });
  });
</script>