<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>Administración</h4>
        </div>
        <div class="flex-fill text-end pt-1">
            <i class="bi bi-gear me-3" style='font-size:30px'></i>
        </div>
    </div>
</div>

<div class="p-1 text-center">
    <button type="button" class="btn btn-outline-primary m-1 p-0" style="width: 72px;" id="users">
        <i class="bi bi-people" style='font-size:40px;'></i>
        <div style="font-size:10px;">Usuarios</div>
    </button>

    <button type="button" class="btn btn-outline-primary m-1 p-0" style="width: 72px;" id="products">
        <i class="bi bi-box" style='font-size:40px;'></i>
        <div style="font-size:10px;">Productos</div>
    </button>

    <button type="button" class="btn btn-outline-primary m-1 p-0" style="width: 72px;" id="clients">
        <i class="bi bi-person-bounding-box" style='font-size:40px;'></i>
        <div style="font-size:10px;">Clientes</div>
    </button>

    <button type="button" class="btn btn-outline-primary m-1 p-0" style="width: 72px;" id="suppliers">
        <i class="bi bi-building-fill-gear" style='font-size:40px;'></i>
        <div style="font-size:10px;">Proveedores</div>
    </button>

    <button type="button" class="btn btn-outline-success m-1 p-0" style="width: 72px;" id="purchase">
        <i class="bi bi-cart-plus" style='font-size:40px;'></i>
        <div style="font-size:10px;">Compras</div>
    </button>
</div>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "index", "body", "");
            });
            $("#users").click(function () {
                show("user", "index", "#view", "");
            });
            $("#products").click(function () {
                show("product", "index", "#view", "");
            });
            $("#clients").click(function () {
                show("client", "index", "#view", "");
            });
            $("#suppliers").click(function () {
                show("supplier", "index", "#view", "");
            });
            $("#purchase").click(function () {
                show("purchase", "index", "#view", "");
            });
        });
    });
</script>