<?php
$pending = [];
$applied = [];
$dispatched = [];
foreach ($this->getAllOrders() as $order) {
    if ($order->status_id == '1') {
        array_push($pending, $order);
    } else if ($order->status_id == '2') {
        array_push($applied, $order);
    } else if ($order->status_id == '3') {
        array_push($dispatched, $order);
    }
}
?>
<div id="view">
    <div class="fixed-top bg-light border-bottom sticky-top">
        <div class="d-flex bd-highlight">
            <div class="text-left px-2">
                <i class="bi bi-book-half" style='font-size:40px'></i>
            </div>
            <div class="flex-fill pt-1">
                <strong style="font-size: 24px;">LA CEIBA</strong>
                <div style="font-size: 11px;">&nbsp;Librería & Papelería</div>
            </div>
            <div class="flex-fill pt-3 pe-2 text-end">
                <span class="badge text-bg-primary">
                    <?php echo $_SESSION["username"]; ?>
                </span>
            </div>
        </div>
    </div>

    <div class="text-center mt-1">
        <button type="button" class="btn btn-primary m-1" style="width: 140px;" id="stock">
            <i class="bi bi-boxes" style='font-size:19px;'></i>
            Inventario
        </button>

        <button type="button" class="btn btn-success m-1" style="width: 140px;" id="addOrder">
            <i class="bi bi-plus-lg" style='font-size:19px;'></i>
            Orden
        </button>
    </div>

    <table class="table">
        <thead>
            <tr>
                <?php if (count($pending) > 0) { ?>
                    <th class="text-center">
                        <div style="font-size: 12px;">
                            <strong>En proceso</strong>
                        </div>
                    </th>
                <?php } ?>

                <?php if (count($applied) > 0) { ?>
                    <th class="text-center">
                        <div style="font-size: 12px;">
                            <strong>Creado</strong>
                        </div>
                    </th>
                <?php } ?>

                <?php if (count($dispatched) > 0) { ?>
                    <th class="text-center">
                        <div style="font-size: 12px;">
                            <strong>Despachado</strong>
                        </div>
                    </th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <?php if (count($pending) > 0) { ?>
                    <td>
                        <div class="d-grid gap-1">
                            <?php foreach ($pending as $ord) { ?>
                                <button class="btn btn-outline-secondary" id="sel<?php echo $ord->id; ?>">
                                    <?php echo "#$ord->id"; ?>
                                    <div style="font-size:9px; text-align: left;">
                                        <?php echo $ord->client; ?>
                                    </div>
                                </button>
                            <?php } ?>
                        </div>
                    </td>
                <?php } ?>

                <?php if (count($applied) > 0) { ?>
                    <td>
                        <div class="d-grid gap-1">
                            <?php foreach ($applied as $ord) { ?>
                                <button class="btn btn-outline-primary" id="sel<?php echo $ord->id; ?>">
                                    <?php echo "#$ord->id"; ?>
                                    <div style="font-size:9px; text-align: left;">
                                        <?php echo $ord->client; ?>
                                    </div>
                                </button>
                            <?php } ?>
                        </div>
                    </td>
                <?php } ?>

                <?php if (count($dispatched) > 0) { ?>
                    <td>
                        <div class="d-grid gap-1">
                            <?php foreach ($dispatched as $ord) { ?>
                                <button class="btn btn-outline-success" id="sel<?php echo $ord->id; ?>">
                                    <?php echo "#$ord->id"; ?>
                                    <div style="font-size:9px; text-align: left;">
                                        <?php echo $ord->client; ?>
                                    </div>
                                </button>
                            <?php } ?>
                        </div>
                    </td>
                <?php } ?>
            </tr>
        </tbody>
    </table>

</div>
<br><br>
<div class="fixed-bottom bg-light border-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="home">
                <i class="bi bi-house" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Inicio</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="admin">
                <i class="bi bi-gear" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Admin</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="mantainer">
                <i class="bi bi-bar-chart-line" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Reportes</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="logout">
                <i class="bi bi-box-arrow-right" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Salir</div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#home").click(function () {
                show("home", "index", "body", "");
            });
            $("#logout").click(function () {
                show("home", "logout", "body", "");
            });
            $("#admin").click(function () {
                show("home", "admin", "#view", "");
            });
            $("#stock").click(function () {
                show("home", "stock", "#view", "");
            });
            $("#addOrder").click(function () {
                show("sale", "selectClient", "#view", "");
            });

            <?php
            if (count($pending) > 0) {
                foreach ($pending as $ord) {
                    ?>
                    $("#sel<?php echo $ord->id; ?>").click(function () {
                        show("sale", "editOrder", "#view", "saleId=<?php echo $ord->id; ?>");
                    });
                <?php
                }
            }
            ?>

            <?php
            if (count($applied) > 0) {
                foreach ($applied as $ord) {
                    ?>
                    $("#sel<?php echo $ord->id; ?>").click(function () {
                        show("sale", "editOrder", "#view", "saleId=<?php echo $ord->id; ?>");
                    });
                <?php
                }
            }
            ?>

            <?php
            if (count($dispatched) > 0) {
                foreach ($dispatched as $ord) {
                    ?>
                    $("#sel<?php echo $ord->id; ?>").click(function () {
                        show("sale", "editOrder", "#view", "saleId=<?php echo $ord->id; ?>");
                    });
                <?php
                }
            }
            ?>
        });
    });
</script>