<div id="view">
    <div class="fixed-top bg-light border-bottom sticky-top">
        <div class="d-flex bd-highlight">
            <div class="text-left px-2">
                <i class="bi bi-book-half" style='font-size:40px'></i>
            </div>
            <div class="flex-fill pt-1">
                <strong style="font-size: 24px;">LA CEIBA</strong>
                <div style="font-size: 11px;">&nbsp;Librería & Papelería</div>
            </div>
            <div class="flex-fill pt-3 pe-2 text-end">
                <span class="badge text-bg-primary">
                    <?php echo $_SESSION["username"]; ?>
                </span>
            </div>
        </div>
    </div>

    <div class="text-center mt-1">
        <button type="button" class="btn btn-primary m-1" style="width: 140px;" id="inventory">
            <i class="bi bi-boxes" style='font-size:19px;'></i>
            Inventario
        </button>

        <button type="button" class="btn btn-success m-1" style="width: 140px;" id="add">
            <i class="bi bi-plus-lg" style='font-size:19px;'></i>
            Orden
        </button>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th class="text-center">Pendientes</th>
                <th class="text-center">Generada</th>
                <th class="text-center">Despachado</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <div class="d-grid gap-1">
                        <button class="btn btn-outline-secondary" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                        <button class="btn btn-outline-secondary" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                    </div>
                </td>
                <td>
                    <div class="d-grid gap-1">
                        <button class="btn btn-outline-primary" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                        <button class="btn btn-outline-primary" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                    </div>
                </td>
                <td>
                    <div class="d-grid gap-1">
                        <button class="btn btn-outline-success" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                        <button class="btn btn-outline-success" type="button">
                            #1
                            <div style="font-size:9px; text-align: left;">
                                Nombre Cliente
                            </div>
                        </button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

</div>
<br><br>
<div class="fixed-bottom bg-light border-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="home">
                <i class="bi bi-house" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Inicio</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="admin">
                <i class="bi bi-gear" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Admin</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="mantainer">
                <i class="bi bi-bar-chart-line" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Reportes</div>
        </div>

        <div class="flex-fill bd-highlight text-center">
            <button class="btn btn-link m-0 p-0" id="logout">
                <i class="bi bi-box-arrow-right" style='font-size:27px'></i>
            </button>
            <div style="font-size: 10px;">Salir</div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#home").click(function () {
                show("home", "index", "body", "");
            });
            $("#logout").click(function () {
                show("home", "logout", "body", "");
            });
            $("#admin").click(function () {
                show("home", "admin", "#view", "");
            });
        });
    });
</script>