<div class="container">
	<div class="row">
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
		<div class="col-md-4 col-sm-6 col-xs-10"
			style="position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);">
			<?php if ($this->getError() != '') { ?>
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
					<strong>Error!</strong> <?php echo $this->getError(); ?>
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			<?php } ?>
			<div class="card border-dark">
				<h5 class="card-header text-white" style="background-color: #343a40!important;">
					<i class="bi bi-shield-shaded"></i>
					Acceso al sistema
				</h5>
				<div class="card-body">
					<form id="form" action="javascript:void(0);" enctype="multipart/form-data">
						<div class="input-group input-group">
							<span class="input-group-text">
								<i class="bi bi-person-check-fill"></i>
							</span>
							<input type="text" class="form-control" name="username" placeholder="Ingresa tu usuario" />
						</div>

						<div class="input-group input-group mt-2">
							<span class="input-group-text">
								<i class="bi bi-key-fill"></i>
							</span>
							<input type="password" class="form-control" name="password"
								placeholder="Ingresa tu contraseña" />
						</div>

						<div class="d-grid col-12 mx-auto mt-2">
							<button type="submit" class="btn btn-success">
								<strong>Ingresar</strong>
								<i class="bi bi-box-arrow-in-right"></i>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
	</div>
</div>

<script>
	$(document).ready(function () {
		$.getScript("lib/vcl/nav.js", function () {
			$("#form").submit(function (event) {
				show("home", "setLogin", "body", $(this).serialize());
			});
		});
	});
</script>