<?php $products = $this->getStock(); ?>
<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>
                Inventario
            </h4>
        </div>
        <div class="flex-fill text-end pt-1">
            <i class="bi bi-boxes me-3" style='font-size:30px'></i>
        </div>
    </div>
</div>

<?php $this->search(); ?>

<div class="accordion mt-2 mb-3" id="accordionExample">
    <div class="d-flex mb-1 border-bottom" style="font-size:17px;font-weight: bold;">
        <div class="flex-grow-1 ms-2">
            Producto
        </div>
        <div class="me-3">
            Disponible
        </div>
    </div>
    <?php
    foreach ($products as $product) {
        $available = $product->stock - $product->pending;
        ?>
        <div class="accordion-item px-0">
            <h2 class="accordion-header" id="head<?php echo $product->id; ?>">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapse<?php echo $product->id; ?>" aria-expanded="false"
                    aria-controls="collapse<?php echo $product->id; ?>">
                    <div class="d-flex me-1" style="width: 100%;">
                        <div class="flex-grow-1">
                            <?php echo $product->name; ?>
                        </div>
                        <div class="ps-1 text-end">
                            <?php echo $this->getBadge($available); ?>
                        </div>
                    </div>
                </button>
            </h2>
            <div id="collapse<?php echo $product->id; ?>" class="accordion-collapse collapse"
                aria-labelledby="head<?php echo $product->id; ?>" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div style="font-size: 14px;">
                        <?php echo $product->description; ?>
                    </div>
                    <div class="d-flex">
                        <div class="p-2 flex-fill text-center">
                            <div style="font-size: 21px;">
                                <?php echo $product->stock; ?>
                            </div>
                            En bodega
                        </div>
                        <div class="p-2 flex-fill text-center">
                            <div style="font-size: 21px;">
                                <?php echo $product->pending; ?>
                            </div>
                            En curso
                        </div>
                        <div class="p-2 flex-fill text-center">
                            <div style="font-size: 21px;">
                                <?php echo $available; ?>
                            </div>
                            Disponible
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php
    } ?>
</div>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "index", "body", "");
            });
        });
    });
</script>