INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 1 OZ ','GOMA TUCAN 1 ONZA',2,2.75);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 2 OZ ','GOMA TUCAN 2 ONZAS ',2.5,3.5);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 4 OZ','GOMA TUCAN 4 ONZAS',3.5,5);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 8 OZ','GOMA TUCAN 8 ONZAS',7.5,10);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 1 OZ 6','GOMA TUCAN 1 ONZA MEDIA DOCENA',12,16.5);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 2 OZ 6','GOMA TUCAN 2 ONZAS MEDIA DOCENA ',15,21);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 4 OZ 6','GOMA TUCAN 4 ONZAS MEDIA DOCENA',21,30);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 8 OZ 6','GOMA TUCAN 8 ONZAS MEDIA DOCENA ',45,60);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 1 OZ 12','GOMA TUCAN 1 ONZA DOCENA',24,33);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 2 OZ 12','GOMA TUCAN 2 ONZAS DOCENA',30,42);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 4 OZ 12','GOMA TUCAN 4 ONZAS DOCENA',42,60);
INSERT INTO products (name, description, cost, price) VALUES ('GOMA TUCAN 8 OZ 12','GOMA TUCAN 8 ONZAS DOCENA',90,120);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. L6','CUADERNO 40 HOJAS CON LINEAS, MEDIA DOCENA',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. C6','CUADERNO 40 HOJAS CON CUADROS, MEDIA DOCENA',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. DL6','CUADERNO 40 HOJAS, DOBLE LINEA MEDIA DOCENA',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. B6','CUADERNO 40 HOJAS, EN BLANCO MEDIA DOCENA',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. L12','CUADERNO 40 HOJAS, CON LINEAS DOCENA',18,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. C12','CUADERNO 40 HOJAS, CON CUADROS, DOCENA',18,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. DL12','CUADERNO 40 HOJAS, DOBLE LINEA, DOCENA',18,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 40H. B12','CUADERNO 40 HOJAS, EN BLANCO, DOCENA',18,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. L6','CUADERNO 80 HOJAS, CON LINEAS MEDIA DOCENA',14.4,19.5);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. C6','CUADERNO 80 HOJAS, CON CUADROS MEDIA DOCENA',14.4,19.5);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. DL6','CUADERNO 80 HOJAS, DOBLE LINEA MEDIA DOCENA',14.4,19.5);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. B6','CUADERNO 80 HOJAS, EN BLANCO MEDIA DOCENA',14.4,19.5);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. L12','CUADERNO 80 HOJAS, CON LINEAS DOCENA',28.8,39);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. C12','CUADERNO 80 HOJAS, CON CUADROS DOCENA',28.8,39);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. DL12','CUADERNO 80 HOJAS, DOBLE LINEAS DOCENA',28.8,39);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 80H. B12','CUADERNO 80 HOJAS, EN BLANCO DOCENA',28.8,39);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. L6','CUADERNO 100 HOJAS CON LINEAS MEDIA DOCENA',17.5,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. C6','CUADERNO 100 HOJAS CON CUADROS MEDIA DOCENA',17.5,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. DL6','CUADERNO 100 HOJAS DOBLE LINEA, MEDIA DOCENA',17.5,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. B6','CUADERNO 100 HOJAS, EN BLANCO MEDIA DOCENA',17.5,24);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. L12','CUADERNO 100 HOJAS CON LINEAS DOCENA',35,48);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. C12','CUADERNO 100 HOJAS CON CUADROS DOCENA',35,48);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. DL12','CUADERNO 100 HOJAS, DOBLE LINEA DOCENA',35,48);
INSERT INTO products (name, description, cost, price) VALUES ('CUADERNO 100H. B12','CUADERNO 100 HOJAS, EN BLANCO, DOCENA',35,48);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 30ML','SILICON 30ML',2.7,3.5);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 60ML','SILICON 60ML',3.75,5);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 100ML','SILICON 100ML',5.5,6.5);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 250ML','SILICON 250ML',10.5,14);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 30ML 6','SILICON 30ML MEDIA DOCENA',16.2,21);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 60ML 6','SILICON 60ML MEDIA DOCENA',22.5,30);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 100ML 6','SILICON 100ML MEDIA DOCENA',33,39);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 250ML 6','SILICON 250ML MEDIA DOCENA',63,84);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 30ML 12','SILICON 30ML DOCENA',32.4,42);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 60ML 12','SILICON 60ML DOCENA',45,60);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 100ML 12','SILICON 100ML DOCENA',66,78);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON 250ML 12','SILICON 250ML DOCENA',126,168);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN CORTO','CRAYON TUCAN CORTO ',3.75,5);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN LARGO','CRAYON TUCAN LARGO',6.95,9);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN CORTO 6','CRAYON TUCAN CORTO MEDIA DOCENA',22.5,30);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN LARGO 6','CRAYON TUCAN LARGO MEDIA DOCENA',41.7,54);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN CORTO 12','CRAYON TUCAN CORTO DOCENA',45,60);
INSERT INTO products (name, description, cost, price) VALUES ('CRAYON TUCAN LARGO 12','CRAYON TUCAN LARGO DOCENA',83.4,108);
INSERT INTO products (name, description, cost, price) VALUES ('MARCADOR FABIK','MARCADOR FABIK',8,10);
INSERT INTO products (name, description, cost, price) VALUES ('MARCADOR FABIK 6','MARCADOR FABIK MEDIA DOCENA',48,60);
INSERT INTO products (name, description, cost, price) VALUES ('MARCADOR FABIK 12','MARCADOR FABIK DOCENA',96,120);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA 100','PAPEL CHINA SURTIDO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA 50','PAPEL CHINA SURTIDO MEDIO CIENTO',16,20);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA AZUL 100','PAPEL CHINA AZUL 100UNI ',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA BLANCO 100','PAPEL CHINA BLANCO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA ROSADO 100','PAPEL CHINA ROSADO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA CAFÉ 100','PAELCHINA CAFÉ 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA NEGRO 100','PAPEL CHINA NEGRO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA VERDE 100','PAPEL CHINA VERDE 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA VERDE LIMON 100','PAPEL CHINA VERDE LIMON 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA MORADO 100','PAPEL CHINA MORADO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPELCHINA ANARANJADO 100','PAPEL CHINA ANARANJADO 100UNI ',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA ROJO 100','PAPEL CHINA ROJO 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA FUCSIA 100','PAPEL CHINA FUCSIA 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA CELESTE 100','PAPEL CHINA CELESTE 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA TURQUESA 100','PAPEL CHINA TURQUESA 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('PAPEL CHINA GRIS 100','PAPEL CHINA GRIS 100UNI',32,40);
INSERT INTO products (name, description, cost, price) VALUES ('OJITOS MOBIBLES','OJITOS MOBIBLES, COLORES, CARTON',11,15);
INSERT INTO products (name, description, cost, price) VALUES ('OJITOS MOBIBLES BN','OJITOS MOBIBLES, BLANCO Y NEGRO',11,15);
INSERT INTO products (name, description, cost, price) VALUES ('BOTE DE SACAPUNTAS','SACAPUNTAS TUCAN, BOTE 48UNI',17,35);
INSERT INTO products (name, description, cost, price) VALUES ('SACAPUNTAS CHINA','SACAPUNTAS CHINA, BOTE 72UNI',12,20);
INSERT INTO products (name, description, cost, price) VALUES ('BORRADOR POINTER PEQ','BORRADOR POINTER PEQUEÑA, CAJA 60UNI',15,25);
INSERT INTO products (name, description, cost, price) VALUES ('BORRADOR POINTER G','BORRADOR POINTER GRANDE, CAJA 30UNI',15,22);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC NEGRO','LAPICERO BIC NEGRO, DOCENA',12,16);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC AZUL','LAPICERO BIC AZUL, DOCENA',12,16);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC ROJO','LAPICERO BIC ROJO, DOCENA',12,16);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC NEGRO 12C','LAPICERO BIC NEGRO, GRUESA 12CAJAS',144,180);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC AZUL 12C','LAPICERO BIC AZUL, GRUESA 12CAJAS',144,180);
INSERT INTO products (name, description, cost, price) VALUES ('LAPICERO BIC ROJO 12C','LAPICERO BIC ROJO, GRUESA 12CAJAS',144,180);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK ARCOIRIS OF','BLOK ARCOIRIS OFICIO ',11,17);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK ARCOIRIS CA','BLOK ARCOIRIS CARTA',10.5,15);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK CONSTRUCCION OF','BLOK CONSTRUCCION CARTA',7.5,10);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK CONSTRUCCION CA','BLOK CONSTRUCCION OFICIO',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK CASCARA DE HUEVO','BLOK CASCARA DE HUEVO CARTA',15,20);
INSERT INTO products (name, description, cost, price) VALUES ('BLOK PAPEL BONDDOBLE OFICIO','BLOK PAPEL BOND DOBLE OFICIO',22,35);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON BARRA D','SILICON BARRA DELGADA 1KILO',35,50);
INSERT INTO products (name, description, cost, price) VALUES ('SILICON BARRA G','SILICON BARRA GRUESA 1KILO',35,50);
INSERT INTO products (name, description, cost, price) VALUES ('GANCHO P/FOLDER M','GANCHO METAL, PARA FOLDER, 50UNI',9,12);
INSERT INTO products (name, description, cost, price) VALUES ('GANCHO P/FOLDER P','GANCHO PLASTICO, PARA FOLDER, 50UNI',8,10);