<div class="d-flex bd-highlight bg-light border-bottom fixed-top">
    <div class="text-left px-2">
        <img src=" /images/ceiba.png" alt="Logo" height="45" class="mt-2">
    </div>
    <div class="flex-fill pt-1">
        <strong style="font-size: 24px;">LA CEIBA</strong>
        <div style="font-size: 11px;">&nbsp;Librería & Papelería</div>
    </div>
    <div class="flex-fill pt-2 pe-2 text-end">
        usuario
        <div style="font-size:11px;">admin</div>
    </div>
</div>

<br><br><br>