<?php
$user = $this->getUser();
$nuevo = $user->id == '';
?>
<div class="fixed-top bg-light border-bottom sticky-top">
  <div class="d-flex bd-highlight">
    <div class="flex-fill text-left">
      <button class="btn btn-link" id="back">
        <i class="bi bi-chevron-left" style='font-size:27px'></i>
      </button>
    </div>
    <div class="flex-fill text-center pt-3">
      <h4>
        <?php echo $nuevo ? 'Crear' : 'Editar'; ?> Usuario
      </h4>
    </div>
    <div class="flex-fill text-end pt-1">
      <i class="bi bi-person-<?php echo $nuevo ? 'add' : 'gear'; ?> me-3" style='font-size:30px'></i>
    </div>
  </div>
</div>

<div class="container">
  <form class="form-floating was-validated" id="form" action="javascript:void(0);" enctype="multipart/form-data">
    <input name="id" type="hidden" value="<?php echo $user->id; ?>" />

    <div class="form-floating my-2">
      <input type="text" class="form-control" name="username" placeholder="username"
        value="<?php echo $user->username; ?>" required>
      <label for="floatingInput">Username</label>
    </div>

    <div class="form-floating mb-2">
      <input type="text" class="form-control" name="password" placeholder="password"
        value="<?php echo $user->password; ?>" required>
      <label for="floatingInput">Password</label>
    </div>

    <div class="form-floating mb-2">
      <input type="text" class="form-control" name="name" placeholder="name" value="<?php echo $user->name; ?>">
      <label for="floatingInput">Nombre</label>
    </div>

    <div class="text-end mt-3">
      <?php if (!$nuevo) { ?>
        <button class="btn btn-danger" id="delete">
          <i class="bi bi-trash"></i>
          Eliminar
        </button>
      <?php } ?>
      <button class="btn btn-primary" type="submit">
        <i class="bi bi-save"></i>
        Guardar
      </button>
    </div>
  </form>
</div>

<script>
  $(document).ready(function () {
    $.getScript("lib/vcl/nav.js", function () {
      $("#back").click(function () {
        show("user", "index", "#view", "");
      });
      $("#form").submit(function (event) {
        show("user", "save", "#view", $(this).serialize());
      });
      $("#delete").click(function () {
        show("user", "delete", "#view", "id=<?php echo $user->id; ?>");
      });
    });
  });
</script>