<?php
$users = $this->getAllUsers();
?>
<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>Usuarios</h4>
        </div>
        <button class="btn btn-link" id="search">
            <i class="bi bi-search" style='font-size:24px'></i>
        </button>
        <button class="btn btn-link" id="add">
            <i class="bi bi-plus-lg" style='font-size:27px'></i>
        </button>
    </div>
</div>

<?php $this->search(); ?>

<table class="table">
    <thead>
        <tr>
            <th>Usuario</th>
            <th colspan="2">Nombre</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->username; ?></td>
                <td>
                    <?php echo $user->name; ?>
                </td>
                <td>
                    <button class="btn btn-link m-0 p-0" id="edit<?php echo $user->id; ?>">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "index", "body", "");
            });
            $("#add").click(function () {
                show("user", "edit", "#view", "");
            });
            $("#search").click(function () {
                show("user", "filter", "#filter", "");
            });
<?php foreach ($users as $user) { ?>
                    $("#edit<?php echo $user->id; ?>").click(function () {
                        show("user", "edit", "#view", "id=<?php echo $user->id; ?>");
                    });    
<?php } ?>
        });
    });
</script>