<?php
$sale = $this->getCurrent();
$isEditing = $sale->status_id == '1';
?>

<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>
                <?php echo $isEditing ? 'Nueva' : ''; ?> Orden
            </h4>
        </div>
        <div class="flex-fill text-end pt-2 pe-2">
            <a class="btn btn-sm btn-outline-<?php echo $isEditing ? 'primary' : 'secondary'; ?>" href="#"
                id="<?php echo $isEditing ? 'finish' : 'edit'; ?>">
                <i class="bi bi-<?php echo $isEditing ? 'check-circle' : 'pencil-square'; ?>"></i>
                <?php echo $isEditing ? 'Finalizar' : 'Editar'; ?>
            </a>
        </div>
    </div>
</div>

<div class="d-flex my-2 mx-2">
    <div class="p-1 flex-grow-1">
        <div style="font-size:10px;">Cliente</div>
        <?php echo $sale->client; ?>
    </div>
    <div class="p-1">
        <div style="font-size:10px;">Fecha</div>
        <?php echo date('d M Y', strtotime($sale->date)); ?>
    </div>
</div>

<?php
if ($isEditing) {
    $tab = $this->getTab();
    $products = $tab == '1' ? $this->getProductsToAdd($sale->id) : $this->getProducts($sale->id);
    $params = "preAction=editOrder&saleId=$sale->id&tab=$tab";
    ?>

    <ul class="nav nav-tabs mx-1" style="font-size: 14px;">
        <li class="nav-item">
            <a class="nav-link <?php echo $tab == '1' ? 'active' : ''; ?>" ref="#" id="tabAdd">
                <i class="bi bi-plus"></i> Agregar
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php echo $tab == '2' ? 'active' : ''; ?>" href="#" id="tabList">
                <i class="bi bi-list-check"></i> Listado
            </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="#" id="search">
                <i class="bi bi-search"></i> Buscar
            </a>
        </li>
    </ul>

    <?php $this->search($params); ?>

    <div class="accordion mt-2 mb-3" id="accordionExample">
        <?php 
        if ($tab != '1') { 
            $total = 0;
            foreach ($products as $product) {
                $total += $product->quantity*$product->product_price;
            }    
            
            ?>
        <div class="text-end me-3 my-2">
            <strong>Total: Q.<?php echo number_format($total, 2, '.', ',');?></strong>
        </div>
        <?php } ?>
        <div class="d-flex mb-1 border-bottom">
            <div class="flex-grow-1 ms-2">
                Producto
            </div>
            <div class="me-3">
                <?php echo $tab == '1' ? "Disponible" : "Total/Prod"; ?>
            </div>
        </div>
        <?php
        foreach ($products as $product) {
            if ($tab == '1') {
                $available = $product->stock - $product->pending;
                ?>
                <div class="accordion-item px-0">
                    <h2 class="accordion-header" id="head<?php echo $product->id; ?>">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapse<?php echo $product->id; ?>" aria-expanded="false"
                            aria-controls="collapse<?php echo $product->id; ?>">
                            <div class="d-flex me-1" style="width: 100%;">
                                <div class="flex-grow-1">
                                    <?php echo $product->name; ?>
                                    <div style="font-size: 8px;">
                                        <?php echo $product->description; ?>
                                    </div>
                                </div>
                                <div class="ps-1 text-center">
                                    <?php echo $this->getBadge($available); ?>
                                </div>
                            </div>
                        </button>
                    </h2>
                    <div id="collapse<?php echo $product->id; ?>" class="accordion-collapse collapse"
                        aria-labelledby="head<?php echo $product->id; ?>" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div class="d-flex" style="width: 100%;">
                                <div class="p-1 text-center flex-fill">
                                    <?php echo "Q." . number_format($product->price, 2, '.', ','); ?>
                                    <div style="font-size:10px">Precio</div>
                                </div>
                                <div class="p-1 text-center flex-fill">
                                    <div id="total<?php echo $product->id; ?>">Q.0.00</div>
                                    <div style="font-size:10px">Total</div>
                                </div>
                                <div class="p-1">
                                    <input type="number" class="form-control" id="quantity<?php echo $product->id; ?>"
                                        placeholder="0" style="width: 75px;">
                                </div>
                                <div class="p-1">
                                    <button type="button" class="btn btn-primary" id="prod<?php echo $product->id; ?>">
                                        <i class="bi bi-plus-lg"></i>
                                    </button>
                                </div>
                            </div>

                            <script>
                                $(document).ready(function () {
                                    $("#quantity<?php echo $product->id; ?>").on("keyup", function () {
                                        var total = $("#quantity<?php echo $product->id; ?>").val() * <?php echo $product->price; ?>;
                                        const tot = total.toFixed(2).toLocaleString('en-US', {
                                            maximumFractionDigits: 2
                                        });
                                        $("#total<?php echo $product->id; ?>").html("Q." + tot);
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            <?php
            } else {
                $available = $product->stock - $product->pending;
                ?>
                <div class="accordion-item px-0">
                    <h2 class="accordion-header" id="head<?php echo $product->id; ?>">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapse<?php echo $product->id; ?>" aria-expanded="false"
                            aria-controls="collapse<?php echo $product->id; ?>">
                            <div class="d-flex me-1" style="width: 100%;font-size:13px;">
                                <div class="flex-grow-1">
                                    <?php echo $product->name; ?>
                                    <div style="font-size: 8px;">
                                        <?php echo $product->description; ?>
                                    </div>
                                </div>
                                <div class="ps-1 text-end">
                                    <?php echo "Q." . number_format($product->price * $product->quantity, 2, '.', ','); ?>
                                </div>
                            </div>
                        </button>
                    </h2>
                    <div id="collapse<?php echo $product->id; ?>" class="accordion-collapse collapse"
                        aria-labelledby="head<?php echo $product->id; ?>" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div class="d-flex" style="width: 100%;">
                                <div class="p-1 text-center flex-fill">
                                    <?php echo "Q." . number_format($product->price, 2, '.', ','); ?>
                                    <div style="font-size:10px">Precio</div>
                                </div>
                                <div class="p-1 text-center flex-fill">
                                    <div id="total<?php echo $product->id; ?>">
                                        <?php echo "Q." . number_format($product->product_price * $product->quantity, 2, '.', ','); ?>
                                    </div>
                                    <div style="font-size:10px">Nuevo Total</div>
                                </div>
                                <div class="p-1 text-center flex-fill">
                                    <div id="available<?php echo $product->id; ?>">
                                        <?php echo $available; ?>
                                    </div>
                                    <div style="font-size:10px">Disponible</div>
                                </div>
                            </div>

                            <div class="input-group">
                                <input type="number" class="form-control" placeholder="0" value="<?php echo $product->quantity; ?>"
                                    aria-label="Cantidad de producto" id="quantity<?php echo $product->movId; ?>">
                                <button class="btn btn-outline-success" type="button" id="save<?php echo $product->movId; ?>">
                                    <i class="bi bi-save"></i>
                                    Guardar
                                </button>
                                <button class="btn btn-outline-danger" type="button" id="del<?php echo $product->movId; ?>">
                                    <i class="bi bi-trash"></i>
                                    Eliminar
                                </button>
                            </div>

                            <script>
                                $(document).ready(function () {
                                    $("#quantity<?php echo $product->movId; ?>").on("keyup", function () {
                                        var total = $("#quantity<?php echo $product->movId; ?>").val() * <?php echo $product->product_price; ?>;
                                        const tot = total.toFixed(2).toLocaleString('en-US', {
                                            maximumFractionDigits: 2
                                        });
                                        $("#total<?php echo $product->id; ?>").html("Q." + tot);

                                        var available = <?php echo $available + $product->quantity; ?> - parseInt($("#quantity<?php echo $product->movId; ?>").val());
                                        const ava = available.toFixed(2).toLocaleString('en-US', {
                                            maximumFractionDigits: 2
                                        });
                                        $("#available<?php echo $product->id; ?>").html(available);
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            <?php
            }
        } ?>
    </div>

    <?php $this->pagination($params); ?>

<?php
} else {
    $products = $this->getAllProducts($sale->id);
    $total = 0;
    foreach ($products as $product) {
        $total += $product->quantity*$product->product_price;
    }    
    ?>
    <div class="text-end me-3 my-2">
        <strong>Total: Q.<?php echo number_format($total, 2, '.', ',');?></strong>
    </div>       

    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Total/Prod</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($products as $product) {
                ?>
                <tr>
                    <td>
                        <?php echo $product->name; ?>
                        <div style="font-size: 9px;">
                            <?php echo $product->description; ?>
                        </div>
                    </td>
                    <td class="text-end align-middle pe-3">
                        <?php echo "Q." . number_format($product->product_price * $product->quantity, 2, '.', ','); ?>
                        <div style="font-size: 9px;">
                            <?php echo "$product->quantity u a Q.$product->product_price c/u"; ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php
}
?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "index", "body", "");
            });
            $("#tabAdd").click(function () {
                show("sale", "editOrder", "#view", "saleId=<?php echo $sale->id; ?>&tab=1");
            });
            $("#tabList").click(function () {
                show("sale", "editOrder", "#view", "saleId=<?php echo $sale->id; ?>&tab=2");
            });
            $("#finish").click(function () {
                show("sale", "finish", "#view", "saleId=<?php echo $sale->id; ?>");
            });
            $("#edit").click(function () {
                show("sale", "backToEdit", "#view", "saleId=<?php echo $sale->id; ?>");
            });

            <?php
            if ($isEditing) {
                foreach ($products as $product) {
                    if ($tab == '1') { ?>
                        $("#prod<?php echo $product->id; ?>").click(function () {
                            show("sale", "addProduct", "#view",
                                "<?php echo $params ?>&quantity=" + $("#quantity<?php echo $product->id; ?>").val()
                                + "&productId=<?php echo $product->id; ?>&price=<?php echo $product->price; ?>");
                        });
                    <?php
                    } else {
                        ?>
                        $("#save<?php echo $product->movId; ?>").click(function () {
                            show("sale", "updateQuantity", "#view",
                                "<?php echo $params ?>&quantity=" + $("#quantity<?php echo $product->movId; ?>").val()
                                + "&movId=<?php echo $product->movId; ?>");
                        });

                        $("#del<?php echo $product->movId; ?>").click(function () {
                            show("sale", "deleteMovement", "#view",
                                "<?php echo $params ?>&movId=<?php echo $product->movId; ?>");
                        });
                    <?php
                    }
                }
            }
            ?>
        });
    });
</script>