<?php
$product = $this->getProduct();
$new = $product->id == '';
?>
<div class="fixed-top bg-light border-bottom sticky-top">
  <div class="d-flex bd-highlight">
    <div class="flex-fill text-left">
      <button class="btn btn-link" id="back">
        <i class="bi bi-chevron-left" style='font-size:27px'></i>
      </button>
    </div>
    <div class="flex-fill text-center pt-3">
      <h4>
        <?php echo $new ? 'Crear' : 'Editar'; ?> Producto
      </h4>
    </div>
    <div class="flex-fill text-end pt-1">
      <i class="bi bi-<?php echo $new ? 'plus' : 'pencil'; ?>-square me-3" style='font-size:30px'></i>
    </div>
  </div>
</div>

<div class="container">
  <form class="form-floating was-validated" id="form" action="javascript:void(0);" enctype="multipart/form-data">
    <input name="id" type="hidden" value="<?php echo $product->id; ?>" />

    <div class="form-floating my-2">
      <input type="text" class="form-control" name="name" placeholder="nombre" value="<?php echo $product->name; ?>"
        required autofocus>
      <label for="floatingInput">Nombre</label>
    </div>

    <div class="form-floating mb-2">
      <input type="text" class="form-control" name="description" placeholder="Descripcion"
        value="<?php echo $product->description; ?>">
      <label for="floatingInput">Descripción</label>
    </div>

    <div class="form-floating mb-2">
      <input type="number" name="cost" placeholder="Costo"
        value="<?php echo number_format($product->cost, 2, '.', ','); ?>" class="form-control money" step="0.01"
        placeholder='1.00' min="0.01" required>
      <label for="floatingInput">Costo</label>
    </div>

    <div class="form-floating mb-2">
      <input type="number" name="price" placeholder="Precio"
        value="<?php echo number_format($product->price, 2, '.', ','); ?>" class="form-control money" step="0.01"
        placeholder='1.00' min="0.01" required>
      <label for="floatingInput">Costo</label>
    </div>

    <div class="text-end mt-3">
      <button class="btn btn-primary" type="submit">
        <i class="bi bi-save"></i>
        Guardar
      </button>
      <?php if (!$nuevo) { ?>
        <button class="btn btn-danger" id="delete">
          <i class="bi bi-trash"></i>
          Eliminar
        </button>
      <?php } ?>
    </div>
  </form>
</div>

<script>
  $(document).ready(function () {
    $.getScript("lib/vcl/nav.js", function () {
      $("#back").click(function () {
        show("product", "index", "#view", "<?php echo $this->getBackFiltered(); ?>");
      });
      $("#form").submit(function (event) {
        show("product", "save", "#view", $(this).serialize());
      });
      $("#delete").click(function () {
        show("product", "delete", "#view", "id=<?php echo $product->id; ?>");
      });
      $(".money").change(function () {
        $(this).val(parseFloat($(this).val()).toFixed(2));
      });
    });
  });
</script>