<?php
$products = $this->getAllProducts();
?>
<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>Productos</h4>
        </div>
        <button class="btn btn-link" id="search">
            <i class="bi bi-search" style='font-size:24px'></i>
        </button>
        <button class="btn btn-link" id="add">
            <i class="bi bi-plus-lg" style='font-size:27px'></i>
        </button>
    </div>
</div>

<?php $this->search(); ?>

<div class="accordion mb-2" id="accordionProducts">
    <?php foreach ($products as $product) { ?>

        <div class="accordion-item">
            <h2 class="accordion-header" id="heading<?php echo $product->id; ?>">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapse<?php echo $product->id; ?>"
                    aria-controls="collapse<?php echo $product->id; ?>">
                    <?php echo $product->name; ?>
                </button>
            </h2>
            <div id="collapse<?php echo $product->id; ?>" class="accordion-collapse collapse"
                aria-labelledby="heading<?php echo $product->id; ?>" data-bs-parent="#accordionProducts">
                <div class="accordion-body py-1">
                    <?php if (trim($product->description) != '') { ?>
                        <div style="font-size: 12px;">Descripción</div>
                    <?php } ?>
                    <?php echo $product->description; ?>
                    <div class="row">
                        <div class="col">
                            <div style="font-size: 12px;">Costo</div>
                            Q.
                            <?php echo number_format($product->cost, 2, '.', ','); ?>
                        </div>
                        <div class="col">
                            <div style="font-size: 12px;">Precio</div>
                            Q.
                            <?php echo number_format($product->price, 2, '.', ','); ?>
                        </div>
                        <div class="col position-relative">
                            <button class="btn btn-sm btn-primary position-absolute bottom-0 end-0"
                                id="edit<?php echo $product->id; ?>">
                                <i class="bi bi-pencil-square"></i> Editar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <?php } ?>
</div>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "admin", "#view", "");
            });
            $("#add").click(function () {
                show("product", "edit", "#view", "");
            });
            <?php foreach ($products as $product) { ?>
                $("#edit<?php echo $product->id; ?>").click(function () {
                    show("product", "edit", "#view", "id=<?php echo $product->id; ?>");
                });
            <?php } ?>
        });
    });
</script>