<?php
list($startPage, $page, $pages, $pageList) = $this->getPagination();

$ic = 'ic';
$ctl = $this->controller;
$act = $this->action;
$vie = '#main';
$param = '';

if (count($this->componentParams) == 1) {
    list($ic) = $this->componentParams;
} else if (count($this->componentParams) == 5) {
    list($ic, $ctl, $act, $vie, $par) = $this->componentParams;
    foreach ($par as $p) {
        list($k, $v) = $p;
        $param = ($param == '' ? '' : '&') . "$k=$v";
    }
}
?>

<?php if ($pages > 1) { ?>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php if ($pages > 5) { ?>
                <button class="page-link" id="prev<?php echo $ic; ?>" <?php echo $startPage == 1 ? 'disabled' : ''; ?>>
                    <i class="bi bi-chevron-compact-left"></i>
                </button>
            <?php } ?>

            <?php foreach ($pageList as $item) { ?>
                <li class="page-item <?php echo $item == $page ? 'active' : ''; ?>">
                    <button class="page-link" id="p<?php echo $ic . $item; ?>">
                        <?php echo $item; ?>
                    </button>
                </li>
            <?php } ?>

            <?php if ($pages > 5) { ?>
                <button class="page-link" id="next<?php echo $ic; ?>" <?php echo ($startPage + 4) == $pages ? 'disabled' : ''; ?>>
                    <i class="bi bi-chevron-compact-right"></i>
                </button>
            <?php } ?>
        </ul>
    </nav>

    <script>
        $(document).ready(function () {
            $.getScript("modules/navigate/main.js", function () {
                <?php if ($pages > 5) { ?>
                    <?php if ($startPage != 1) { ?>
                        $("#prev<?php echo $ic; ?>").click(function () {
                            show("<?php echo $ctl; ?>", "<?php echo $act; ?>", "<?php echo $vie; ?>",
                                "page=<?php echo $startPage - 1; ?>&startPage=<?php echo $startPage . '&' . $param; ?>");
                        });
                    <?php } ?>

                    <?php if (($startPage + 4) != $pages) { ?>
                        $("#next<?php echo $ic; ?>").click(function () {
                            show("<?php echo $ctl; ?>", "<?php echo $act; ?>", "<?php echo $vie; ?>",
                                "page=<?php echo $startPage + 5; ?>&startPage=<?php echo $startPage . '&' . $param; ?>");
                        });
                    <?php } ?>
                <?php } ?>

                <?php foreach ($pageList as $item) { ?>
                    $("#p<?php echo $ic . $item; ?>").click(function () {
                        show("<?php echo $ctl; ?>", "<?php echo $act; ?>", "<?php echo $vie; ?>",
                            "page=<?php echo $item; ?>&startPage=<?php echo $startPage . '&' . $param; ?>");
                    });
                <?php } ?>
            });
        });
    </script>
<?php } ?>