<?php
$this->component('pc-nav', [
    [
        [
            "type" => "",
            "icon" => "house",
            "title" => "Inicio",
            "id" => "pur-home",
            "ctl" => "home",
            "act" => "index",
            "vie" => "body",
        ],
        [
            "type" => "",
            "icon" => "",
            "title" => "Compras",
            "id" => "pur-purchase",
            "ctl" => "purchase",
            "act" => "index",
            "vie" => "#main",
        ],
        [
            "type" => "active",
            "icon" => "",
            "title" => "Compra",
            "id" => "",
            "ctl" => "",
            "act" => "",
            "vie" => "#main",
        ],
    ]
]);
?>

<div class="card mb-2">
    <div class="card-body d-flex m-0 p-1">
        <div class="ps-1 flex-fill ">
            <div style="font-size: 12px;">Compra</div>
            #XX
        </div>
        <div class="ps-1 flex-fill">
            <div style="font-size: 12px;">Proveedor</div>
            Nombre de proveedor
        </div>
        <div class="ps-1 flex-fill">
            <div style="font-size: 12px;">Fecha</div>
            23/23/2323
        </div>
        <div class="p-1 flex-fill text-end">
            <button class="btn btn-primary">Editar</button>
        </div>
    </div>
</div>

<div class="d-flex">
    <div class="flex-fill me-2" id="prodtoadd">
        <?php $this->prodToAdd(); ?>
    </div>
    <div class="flex-fill">
        <?php $this->prodAdded(); ?>
    </div>
</div>

<?php $this->component('edit-prod'); ?>