<?php
$clients = $this->getAllClients();
?>
<div class="fixed-top bg-light border-bottom sticky-top">
    <div class="d-flex bd-highlight">
        <div class="flex-fill bd-highlight text-left">
            <button class="btn btn-link" id="back">
                <i class="bi bi-chevron-left" style='font-size:27px'></i>
            </button>
        </div>
        <div class="flex-fill text-center pt-3">
            <h4>Clientes</h4>
        </div>
        <button class="btn btn-link" id="search">
            <i class="bi bi-search" style='font-size:24px'></i>
        </button>
        <button class="btn btn-link" id="add">
            <i class="bi bi-plus-lg" style='font-size:27px'></i>
        </button>
    </div>
</div>

<?php $this->search(); ?>

<div class="accordion mb-2" id="accordionClients">
    <?php foreach ($clients as $client) { ?>
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading<?php echo $client->id; ?>">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapse<?php echo $client->id; ?>" aria-controls="collapse<?php echo $client->id; ?>">
                    <?php echo $client->name; ?>
                </button>
            </h2>
            <div id="collapse<?php echo $client->id; ?>" class="accordion-collapse collapse"
                aria-labelledby="heading<?php echo $client->id; ?>" data-bs-parent="#accordionClients">
                <div class="accordion-body py-1">
                    <?php if (trim($client->address) != '') { ?>
                        <div style="font-size: 12px;">Dirección</div>
                    <?php } ?>
                    <?php echo $client->address; ?>
                    <?php if (trim($client->reference) != '') { ?>
                        <div style="font-size: 12px;">Referencia</div>
                    <?php } ?>
                    <?php echo $client->reference; ?>
                    <div class="row">
                        <div class="col">
                            <div style="font-size: 12px;">Telefono</div>
                            <?php echo $client->phone; ?>
                        </div>
                        <div class="col position-relative">
                            <button class="btn btn-sm btn-primary position-absolute bottom-0 end-0"
                                id="edit<?php echo $client->id; ?>">
                                <i class="bi bi-pencil-square"></i> Editar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<?php $this->pagination(); ?>

<script>
    $(document).ready(function () {
        $.getScript("lib/vcl/nav.js", function () {
            $("#back").click(function () {
                show("home", "admin", "#view", "");
            });
            $("#add").click(function () {
                show("client", "edit", "#view", "");
            });
            <?php foreach ($clients as $client) { ?>
                $("#edit<?php echo $client->id; ?>").click(function () {
                    show("client", "edit", "#view", "id=<?php echo $client->id; ?>");
                });
            <?php } ?>
        });
    });
</script>