<div class="container">
	<div class="row">
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
		<div class="col-md-4 col-sm-6 col-xs-10"
			style="position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);">
			<div class="card border-dark">
				<h5 class="card-header text-white" style="background-color: #343a40!important;">
					<i class="bi bi-shield-shaded"></i>
					Acceso al sistema
				</h5>
				<div class="card-body">
					<?php $this->component("login-form"); ?>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
	</div>
</div>